name: ImageConverter
api: 3.3.1
main: korado531m7\ImageConverter\ImageConverter
version: 2.2.1
author: korado531m7
description: "Importing photo image and converting it into block"
commands:
 convert:
  description: "Convert image into block"
  permission: imageconverter.convert.command